exclude_patterns:
- ".github/ISSUE_TEMPLATE/"
- "e2e/"
- "ecs/"
- "features/"
- "scripts/"
- "nginx"
- "swagger"
- "docs/"
- "manage.py"
- "**/db/"
- "**/migrations/"
- "**/node_modules/"
- "**/test/"
- "**/tests/"
- "**/test*.py"
- "**/test*.js"
